dodo_arm:
    # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: home_arm
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
      - gripper_roll_joint
      - finger_joint1
      - finger_joint2
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
      - gripper_roll_joint
    gains:
      shoulder_pan_joint:
        p: 100
        d: 10
        i: 0.01
        i_clamp: 1
      shoulder_pitch_joint:
        p: 500
        d: 100
        i: 0.05
        i_clamp: 1
      elbow_pitch_joint:
        p: 800
        d: 100
        i: 0.1
        i_clamp: 1
      wrist_roll_joint:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
      wrist_pitch_joint:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
      gripper_roll_joint:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0
        shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
        shoulder_pitch_joint: {trajectory: 0.1, goal: 0.1}
        elbow_pitch_joint: {trajectory: 0.1, goal: 0.1}
        wrist_roll_joint: {trajectory: 0.1, goal: 0.1}
        wrist_pitch_joint: {trajectory: 0.1, goal: 0.1}
        gripper_roll_joint: {trajectory: 0.1, goal: 0.1}
    state_publish_rate: 25  

  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - finger_joint1
      - finger_joint2
    gains:
      finger_joint1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      finger_joint2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
    state_publish_rate: 25 
     
  gazebo_ros_control/pid_gains:
    shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_pitch_joint: {p: 500.0, i: 0.05, d: 100.0}
    elbow_pitch_joint: {p: 800.0, i: 0.1, d: 100.0}
    wrist_roll_joint: {p: 500.0, i: 0.01, d: 10.0}
    wrist_pitch_joint: {p: 500.0, i: 0.01, d: 10.0}
    gripper_roll_joint: {p: 500.0, i: 0.01, d: 10.0}
    finger_joint1: {p: 500.0, i: 0.01, d: 10.0}
    finger_joint2: {p: 500.0, i: 0.01, d: 10.0}

controller_list:
    - name: dodo_arm/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - shoulder_pan_joint
        - shoulder_pitch_joint
        - elbow_pitch_joint
        - wrist_roll_joint
        - wrist_pitch_joint
        - gripper_roll_joint
    - name: dodo_arm/gripper_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - finger_joint1
        - finger_joint2